name: HS-Ranks
version: 2.1
author: RySty
main: mc.rysty.heliosphereranks.HelioSphereRanks
api-version: 1.16

commands:
  nickname:
    aliases: [nick]
  prefix:
  setgroup:
  grouppermission:
  levelmodify:
  levelinfo:
